fix: `_stat_mode` can follow symlinks pointing to a relative path
eth-cscs/pyfirecrest pull request #113
Opened 2024-07-02 19:29 UTC by khsrali

`_stat_mode` couldn't follow symlinks that are pointing to relative paths. As a result, `_stat_mode` of the symlink was returned instead of the target.

This PR adds an extra check if the target path of a symlink is a relative path; it resolves it.

In addition, a new function `relpath` is added for the sake of completeness. This will prevent users to manually transforming each `FcPath` to `Path` in order to get the relative path.

2024-07-11 07:06 UTC, ekouts requested changes
Thanks a lot for the contributions @khsrali ! I was going to approve, but just noticed that the type check fails, would you have time to take a look to that? :)

The truth is I haven't been maintaining very well `FcPath` even though it is probably interesting to other users as well! No need to do it in this PR, but if it some point you would have some time to add some documentation in rtd it could help me and others :)

2024-07-11 08:38 UTC, khsrali commented
Hi @ekouts ,
Thanks, I'll fix it by tomorrow the latest.

> The truth is I haven't been maintaining very well FcPath even though it is probably interesting to other users as well! No need to do it in this PR, but if it some point you would have some time to add some documentation in rtd it could help me and others :)

Absolutely, you are right, it's good to have some documentation. Will do in a separate PR :)

2024-07-11 09:02 UTC, ekouts commented
Great, thanks!

2024-07-16 06:08 UTC, ekouts approved these changes

2024-07-16 06:09 UTC, merged